generate tt_submission artifacts

diff --git a/.github/workflows/reharden.yaml b/.github/workflows/reharden.yaml
--- a/.github/workflows/reharden.yaml
+++ b/.github/workflows/reharden.yaml
@@ -268,13 +268,49 @@ jobs:
             exit 1
           fi
 
-      - name: Publish build logs
-        #if: failure()
+      #- name: Publish build logs
+      #  #if: success() || failure()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #    name: GDS_${{ matrix.project }}
+      #    path: |
+      #      hdl/${{ matrix.project }}/runs/*
+
+      - name: Install KLayout
+        shell: bash
+        run: |
+          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.11/klayout_0.29.11-1_amd64.deb
+          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.11-1_amd64.deb
+          pip install klayout==0.29.11
+
+      - name: Prepare tt_submission artifact
+        working-directory: hdl/${{ matrix.project }}
+        shell: bash
+        run: |
+          mkdir -p tt_submission/stats
+          TOP_MODULE=$(./tt/tt_tool.py --print-top-module --ihp)
+          cp runs/wokwi/final/commit_id.json tt_submission/
+          cp runs/wokwi/final/{gds,lef,spef/*}/${TOP_MODULE}.* tt_submission/
+          strm2oas tt_submission/${TOP_MODULE}.gds tt_submission/${TOP_MODULE}.oas
+          if [ "$PDK" == "sky130A" ]; then
+            cp runs/wokwi/final/pnl/${TOP_MODULE}.pnl.v tt_submission/${TOP_MODULE}.v
+          else
+            cp runs/wokwi/final/nl/${TOP_MODULE}.nl.v tt_submission/${TOP_MODULE}.v
+          fi
+          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,resolved.json} tt_submission/
+          cp runs/wokwi/final/metrics.csv tt_submission/stats/metrics.csv
+          cp runs/wokwi/*-yosys-synthesis/reports/stat.rpt tt_submission/stats/synthesis-stats.txt
+
+      - name: Publish tt_submission artifact
         uses: actions/upload-artifact@v4
         with:
-          name: GDS_${{ matrix.project }}
+          name: tt_submission_${{ matrix.project }}
           path: |
-            hdl/${{ matrix.project }}/runs/*
+            hdl/${{ matrix.project }}/src/*
+            hdl/${{ matrix.project }}/docs/*
+            hdl/${{ matrix.project }}/tt_submission/*
+            hdl/${{ matrix.project }}/info.yaml
+            hdl/${{ matrix.project }}/LICENSE
 
   reharden-wokwi:
     strategy:
@@ -505,11 +541,47 @@ jobs:
             exit 1
           fi
 
-      - name: Publish build logs
-        #if: failure()
+      #- name: Publish build logs
+      #  #if: failure()
+      #  uses: actions/upload-artifact@v4
+      #  with:
+      #    name: GDS_${{ matrix.project }}
+      #    path: |
+      #      wokwi/${{ matrix.project }}/runs/*
+
+      - name: Install KLayout
+        shell: bash
+        run: |
+          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.11/klayout_0.29.11-1_amd64.deb
+          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.11-1_amd64.deb
+          pip install klayout==0.29.11
+
+      - name: Prepare tt_submission artifact
+        working-directory: wokwi/${{ matrix.project }}
+        shell: bash
+        run: |
+          mkdir -p tt_submission/stats
+          TOP_MODULE=$(./tt/tt_tool.py --print-top-module --ihp)
+          cp runs/wokwi/final/commit_id.json tt_submission/
+          cp runs/wokwi/final/{gds,lef,spef/*}/${TOP_MODULE}.* tt_submission/
+          strm2oas tt_submission/${TOP_MODULE}.gds tt_submission/${TOP_MODULE}.oas
+          if [ "$PDK" == "sky130A" ]; then
+            cp runs/wokwi/final/pnl/${TOP_MODULE}.pnl.v tt_submission/${TOP_MODULE}.v
+          else
+            cp runs/wokwi/final/nl/${TOP_MODULE}.nl.v tt_submission/${TOP_MODULE}.v
+          fi
+          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,resolved.json} tt_submission/
+          cp runs/wokwi/final/metrics.csv tt_submission/stats/metrics.csv
+          cp runs/wokwi/*-yosys-synthesis/reports/stat.rpt tt_submission/stats/synthesis-stats.txt
+
+      - name: Publish tt_submission artifact
         uses: actions/upload-artifact@v4
         with:
-          name: GDS_${{ matrix.project }}
+          name: tt_submission_${{ matrix.project }}
           path: |
-            wokwi/${{ matrix.project }}/runs/*
+            wokwi/${{ matrix.project }}/src/*
+            wokwi/${{ matrix.project }}/docs/*
+            wokwi/${{ matrix.project }}/tt_submission/*
+            wokwi/${{ matrix.project }}/info.yaml
+            wokwi/${{ matrix.project }}/LICENSE
 
